version: "3.8"

services:
  mongo-service:
    container_name: mongo-service
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-data:/data/db
    networks:
      - network-service

  mysql-service:
    container_name: mysql-service
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=mysqltestdb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    networks:
      - network-service

networks:
  network-service:
    driver: bridge
